trigger:
  branches:
    include:
      - main

pr:
  drafts: false
  branches:
    include:
      - main

variables:
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Building
    pool:
      vmImage: $(vmImageName)

    steps:
      - script: npm ci
        displayName: 'Installing Dependencies'

      - script: npm test -- --ci --watchAll=false --passWithNoTests
        displayName: 'Running Unit Test'

      - script: npm run build
        displayName: 'Building React webApp'

      - task: ArchiveFiles@2
        displayName: 'Zipping files'
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          replaceExistingArchive: true

      - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        displayName: Publishing
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
        artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - deployment: Deploy
    displayName: Deploying
    environment: 'dev'
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: Deploying
            inputs:
              appName: 'alexup-dev' 
              azureSubscription: 'AlexUp (68417a70-80ac-4db7-b7a2-46959c7bdf82)'
              appType: 'webAppLinux'
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              runtimeStack: 'NODE|14-lts'
              startUpCommand: 'npm install -g serve && serve -n -l 8080'
    
          - task: CmdLine@2
            displayName: 'Request to WebApp'
            inputs:
              script: |
                response=$(curl --write-out '%{http_code}' --silent --output /dev/null http://app-tuweb-$(envName)-bra.azurewebsites.net)
                echo HTTP code: $response